export const currencyList = [
  { code: 'CNY', name_zh: '人民幣', name_en: 'Renminbi', symbol: '¥' },
  { code: 'HKD', name_zh: '港元', name_en: 'Hong Kong dollar', symbol: '$' },
  {
    code: 'NTD',
    name_zh: '新台幣',
    name_en: 'New Taiwan dollar',
    symbol: 'NT$',
  },
  { code: 'JPY', name_zh: '日元', name_en: 'Japanese yen', symbol: '¥' },
  { code: 'KRW', name_zh: '韓元', name_en: 'South Korean won', symbol: '₩' },
  {
    code: 'SGD',
    name_zh: '新加坡元',
    name_en: 'Singapore dollar',
    symbol: '$',
  },
  { code: 'MYR', name_zh: '令吉', name_en: 'Malaysian ringgit', symbol: 'RM' },
  { code: 'VND', name_zh: '越南盾', name_en: 'Vietnamese đồng', symbol: '₫' },
  { code: 'THB', name_zh: '泰銖', name_en: 'Thai baht', symbol: '฿' },
  { code: 'INR', name_zh: '印度盧比', name_en: 'Indian rupee', symbol: '₨' },
  { code: 'IDR', name_zh: '印尼盾', name_en: 'Indonesian rupiah', symbol: '₨' },
  { code: 'PHP', name_zh: '披索', name_en: 'Philippine peso', symbol: '₱' },
  { code: 'GBP', name_zh: '英鎊', name_en: 'Pound sterling', symbol: '£' },
  { code: 'EUR', name_zh: '歐元', name_en: 'Euro', symbol: '€' },
  { code: 'RUB', name_zh: '盧布', name_en: 'Russian ruble', symbol: '₽' },
  { code: 'PLN', name_zh: '茲羅提', name_en: 'Polish złoty', symbol: 'zł' },
  { code: 'CHF', name_zh: '瑞士法郎', name_en: 'Swiss franc', symbol: 'CHF' },
  { code: 'SEK', name_zh: '瑞典克朗', name_en: 'Swedish krona', symbol: 'kr' },
  { code: 'DKK', name_zh: '丹麥克朗', name_en: 'Danish krone', symbol: 'kr' },
  {
    code: 'NOK',
    name_zh: '挪威克朗',
    name_en: 'Norwegian krone',
    symbol: 'kr',
  },
  {
    code: 'ISK',
    name_zh: '冰島克朗',
    name_en: 'Icelandic króna',
    symbol: 'kr',
  },
  {
    code: 'USD',
    name_zh: '美元',
    name_en: 'United States dollar',
    symbol: '$',
  },
  { code: 'CAD', name_zh: '加拿大元', name_en: 'Canadian dollar', symbol: '$' },
  { code: 'MXN', name_zh: '比索', name_en: 'Mexican peso', symbol: '$' },
  { code: 'BRL', name_zh: '雷亞爾', name_en: 'Brazilian real', symbol: 'R$' },
  { code: 'ARS', name_zh: '比索', name_en: 'Argentine peso', symbol: '$' },
  { code: 'CLP', name_zh: '比索', name_en: 'Chilean peso', symbol: '$' },
  { code: 'COP', name_zh: '比索', name_en: 'Colombian peso', symbol: '$' },
  { code: 'ZAR', name_zh: '蘭特', name_en: 'South African rand', symbol: 'R' },
  { code: 'NGN', name_zh: '奈拉', name_en: 'Nigerian naira', symbol: '₦' },
  { code: 'KES', name_zh: '先令', name_en: 'Kenyan shilling', symbol: 'Sh' },
  { code: 'EGP', name_zh: '埃及鎊', name_en: 'Egyptian pound', symbol: '£' },
  { code: 'MAD', name_zh: '迪拉姆', name_en: 'Moroccan dirham', symbol: 'DH' },
  { code: 'AUD', name_zh: '澳元', name_en: 'Australian dollar', symbol: '$' },
  {
    code: 'NZD',
    name_zh: '紐西蘭元',
    name_en: 'New Zealand dollar',
    symbol: '$',
  },
  { code: 'FJD', name_zh: '斐濟元', name_en: 'Fijian dollar', symbol: '$' },
];
